// =====================================================================
// 19 villes principales — pages ville-hub
// Chaque ville a un contenu unique pour éviter le duplicate content
// =====================================================================

module.exports = [
  {
    slug: 'marseille',
    name: 'Marseille',
    zoneSlug: 'plan-de-cuques-marseille',
    population: '870 000 habitants',
    distance: '10 km du centre',
    travelTime: '15 minutes en voiture',
    intro: "Marseille, deuxième ville de France, est notre marché historique. La majorité de notre clientèle réside dans les <strong>16 arrondissements marseillais</strong>, des quartiers du Vieux-Port au 13e en passant par Le Prado, Mazargues, Saint-Loup ou Saint-Antoine. Notre atelier de Plan-de-Cuques est facilement accessible depuis n'importe quel point de la ville en 15 à 25 minutes selon le trafic.",
    localContext: "Le contexte automobile marseillais est <strong>particulier</strong> : trafic dense, beaucoup de petits trajets urbains qui encrassent prématurément les moteurs diesel, places de parking serrées qui causent les chocs de carrosserie, et stationnement payant qui pousse à la mobilité partagée. Ces particularités expliquent pourquoi nos prestations <strong>décalaminage hydrogène, nettoyage FAP et réparation carrosserie</strong> sont les plus demandées par nos clients marseillais.",
    accessInfo: "Depuis le centre-ville (Vieux-Port, La Joliette), prenez la D4 direction Plan-de-Cuques via la traverse de la Valbarelle (15 minutes hors heures de pointe). Depuis le 11e ou 12e arrondissement, comptez 10-15 minutes via l'avenue de La Timone. Depuis le 13e ou 14e, prenez l'A507 (rocade L2) avec sortie Plan-de-Cuques (12-18 minutes). Stationnement gratuit devant l'atelier, arrêt de bus à 3 minutes à pied.",
    trafficNote: "Évitez les heures de pointe matin (7h30-9h) et soir (17h-19h30) si possible — les délais peuvent doubler sur la rocade. Les samedis matins sont en général très fluides.",
    topServices: ['decalaminage-hydrogene', 'nettoyage-fap', 'mecanique-generale', 'carrosserie-auto'],
    nearbyDistricts: ['Vieux-Port', 'La Joliette', 'Le Prado', 'La Timone', 'Saint-Loup', 'Saint-Antoine', 'Mazargues', 'Castellane', 'Bonneveine', 'Endoume']
  },
  {
    slug: 'plan-de-cuques',
    name: 'Plan-de-Cuques',
    zoneSlug: 'plan-de-cuques-marseille',
    population: '11 000 habitants',
    distance: 'Sur place',
    travelTime: 'Notre commune',
    intro: "<strong>Plan-de-Cuques (13380)</strong> est la commune où se trouve notre atelier, au 1 Avenue des Pères Blancs. Garage Boost est implanté ici depuis plus de 10 ans et nous connaissons parfaitement les habitants, les particularités automobiles locales, les habitudes de circulation et les enjeux des résidents de cette commune des Bouches-du-Rhône limitrophe de Marseille.",
    localContext: "Plan-de-Cuques est une <strong>commune résidentielle</strong> où la majorité des familles disposent de plusieurs véhicules. Notre clientèle locale apprécie particulièrement notre <strong>service de récupération à domicile</strong> (offert au-delà de 200€) qui leur évite tout déplacement. Nous accueillons aussi de nombreux professionnels installés en ZAE locale.",
    accessInfo: "Sur place. Plan-de-Cuques étant une commune compacte (4 km²), notre atelier est accessible en moins de 10 minutes depuis n'importe quel quartier. Stationnement gratuit, arrêt de bus à proximité immédiate, accès facile pour les utilitaires et fourgons.",
    trafficNote: "Aucun problème de trafic particulier sur la commune. Stationnement aisé devant l'atelier en toute heure.",
    topServices: ['mecanique-generale', 'decalaminage-hydrogene', 'reprogrammation-moteur', 'pare-brise'],
    nearbyDistricts: ['Centre-ville', 'Quartier des Pères Blancs', 'Quartier de La Galéane', 'Le Cousin']
  },
  {
    slug: 'allauch',
    name: 'Allauch',
    zoneSlug: 'plan-de-cuques-marseille',
    population: '21 000 habitants',
    distance: '5 km',
    travelTime: '10 minutes',
    intro: "<strong>Allauch (13190)</strong>, célèbre pour ses moulins et sa vue panoramique sur Marseille, est une commune résidentielle limitrophe de Plan-de-Cuques. Beaucoup de nos clients allauchois nous choisissent pour la <strong>proximité géographique</strong> (10 minutes en voiture) et la qualité de service constante depuis 10 ans.",
    localContext: "Le profil automobile d'Allauch est marqué par les <strong>routes de moyenne montagne</strong> et les trajets vallonnés qui sollicitent particulièrement les freins, la suspension et les courroies de distribution. Notre service <strong>mécanique générale et entretien</strong> est très demandé par nos clients allauchois, ainsi que la <strong>reprogrammation moteur</strong> pour les véhicules qui peinent dans les côtes du massif de l'Étoile.",
    accessInfo: "Depuis le centre d'Allauch, prenez la D4F en direction de Plan-de-Cuques. 10 minutes de trajet, route facile et bien dégagée hors heures de pointe. Vous pouvez aussi descendre par la D2 vers Marseille puis remonter sur Plan-de-Cuques — environ 15 minutes mais plus de variété de paysages.",
    trafficNote: "Trafic généralement fluide, sauf en juillet-août avec les touristes des moulins. Préférez le matin pour éviter les ralentissements estivaux.",
    topServices: ['mecanique-generale', 'reprogrammation-moteur', 'decalaminage-hydrogene', 'depannage-remorquage'],
    nearbyDistricts: ['Centre historique', 'Le Logis-Neuf', 'Pichauris', 'La Pounche', 'Le Vieil Allauch']
  },
  {
    slug: 'aubagne',
    name: 'Aubagne',
    zoneSlug: 'aubagne-la-ciotat-cassis',
    population: '46 000 habitants',
    distance: '15 km',
    travelTime: '20 minutes',
    intro: "<strong>Aubagne (13400)</strong> est l'une des principales communes de l'aire urbaine marseillaise, avec une forte densité de PME, artisans et commerçants. Notre clientèle aubagnaise représente une part importante de notre activité — beaucoup nous découvrent par le bouche-à-oreille via les communautés professionnelles locales.",
    localContext: "Le tissu économique d'Aubagne (zones d'activités des Paluds, Camp Major, La Penne) génère beaucoup de demandes pour les <strong>utilitaires</strong> (artisans, livreurs, commerçants), la <strong>mécanique générale flotte</strong> et le <strong>dépannage urgent</strong>. Nous avons développé des <strong>conventions partenariat</strong> avec plusieurs entreprises aubagnaises pour faciliter la gestion de leurs flottes véhicules.",
    accessInfo: "Depuis Aubagne, prenez la D2 puis la D4F en direction de Plan-de-Cuques (15-20 minutes). Alternative plus rapide en heures creuses : A50 jusqu'à La Penne-sur-Huveaune, puis D4F (15 minutes). Notre dépanneuse intervient à Aubagne en 30-45 minutes en cas d'immobilisation.",
    trafficNote: "Trafic chargé sur la D2 entre 17h et 19h. Préférez l'A50 en heures de pointe. Le matin (avant 8h30) et le samedi matin sont fluides.",
    topServices: ['mecanique-generale', 'utilitaires', 'depannage-remorquage', 'carrosserie-auto'],
    nearbyDistricts: ['Centre-ville', 'Les Solans', 'Beaudinard', 'Camp Major', 'Les Paluds', 'La Tourtelle']
  },
  {
    slug: 'la-ciotat',
    name: 'La Ciotat',
    zoneSlug: 'aubagne-la-ciotat-cassis',
    population: '36 000 habitants',
    distance: '24 km',
    travelTime: '30 minutes',
    intro: "<strong>La Ciotat (13600)</strong>, ville côtière entre Marseille et Toulon, dispose d'une importante activité portuaire et touristique. Nos clients ciotadens nous choisissent pour notre <strong>spécialisation moteur</strong> (rare sur la côte) et la qualité constante de nos prestations carrosserie pour les véhicules exposés à l'air marin.",
    localContext: "L'air marin ciotaden a un effet <strong>corrosif spécifique</strong> sur les véhicules : accélération de la rouille sur les bas de caisse, oxydation des éléments métalliques, dégradation prématurée des sondes lambda et capteurs. Nos prestations <strong>traitement anti-corrosion, carrosserie et électricité automobile</strong> sont particulièrement demandées par notre clientèle de La Ciotat.",
    accessInfo: "Depuis La Ciotat, prenez l'A50 direction Marseille puis sortie La Penne-sur-Huveaune et D4F (30 minutes). Trajet sans difficulté hors saison estivale. En été (juillet-août), comptez 45-60 minutes en raison du tourisme.",
    trafficNote: "L'A50 est saturée en juillet-août les week-ends et vacances scolaires. Privilégiez les jours de semaine. La gare SNCF de La Ciotat permet aussi de rejoindre Marseille puis bus.",
    topServices: ['carrosserie-auto', 'electricite-automobile', 'depannage-remorquage', 'reprogrammation-moteur'],
    nearbyDistricts: ['Vieille Ville', 'Le Port', 'La Garoupe', 'Saint-Jean', 'Le Mugel', 'Athéna', 'Les Séveriers']
  },
  {
    slug: 'cassis',
    name: 'Cassis',
    zoneSlug: 'aubagne-la-ciotat-cassis',
    population: '7 200 habitants',
    distance: '24 km',
    travelTime: '30 minutes',
    intro: "<strong>Cassis (13260)</strong>, joyau de la Provence avec ses Calanques classées Parc National, attire une clientèle exigeante en matière de qualité automobile. Nos clients cassidans, propriétaires de berlines et SUV haut de gamme, apprécient particulièrement notre <strong>expertise sur véhicules premium</strong> et notre cabine de peinture professionnelle.",
    localContext: "Le profil automobile de Cassis combine <strong>véhicules de prestige</strong> (Porsche, BMW, Mercedes, Audi) et <strong>contraintes de stationnement</strong> serrées dans le village et le port. Les chocs de carrosserie en stationnement sont fréquents, et nos prestations <strong>débosselage sans peinture (DSP), peinture cabine et polish céramique</strong> sont très demandées par notre clientèle locale.",
    accessInfo: "Depuis Cassis, prenez la D559 vers Marseille puis l'A50 et sortie La Penne-sur-Huveaune (30 minutes hors saison). Route panoramique magnifique mais sinueuse — privilégiez le matin pour la fluidité.",
    trafficNote: "Très chargé en saison estivale (juillet-août) : tourisme international intense. Hors saison, route fluide et très agréable. Jamais de problème en semaine matin.",
    topServices: ['carrosserie-auto', 'peinture-automobile', 'reprogrammation-moteur', 'mecanique-generale'],
    nearbyDistricts: ['Centre village', 'Le Port', 'Bestouan', 'La Couronne', 'Quartier des Calanques']
  },
  {
    slug: 'septemes-les-vallons',
    name: 'Septèmes-les-Vallons',
    zoneSlug: 'plan-de-cuques-marseille',
    population: '11 000 habitants',
    distance: '11 km',
    travelTime: '15 minutes',
    intro: "<strong>Septèmes-les-Vallons (13240)</strong>, commune au nord-est de Marseille, est très proche géographiquement de notre atelier. Nos clients septémois nous choisissent pour la rapidité d'accès et la qualité de notre service de <strong>récupération à domicile</strong>, particulièrement adapté aux familles avec plusieurs véhicules.",
    localContext: "Septèmes-les-Vallons est une commune <strong>résidentielle et péri-urbaine</strong> avec une forte proportion de pavillons et de familles motorisées. Notre service <strong>mécanique générale, vidange et plaquettes de frein</strong> est particulièrement apprécié pour son rapport qualité-prix.",
    accessInfo: "Depuis Septèmes, prenez l'A507 (rocade L2) en direction Aix puis sortie Plan-de-Cuques (15 minutes). Alternative par la D908 (route plus longue mais moins de trafic en heures de pointe).",
    trafficNote: "L'A507 est chargée en heures de pointe matin et soir. Préférez le matin avant 8h ou en milieu de journée.",
    topServices: ['mecanique-generale', 'pare-brise', 'depannage-remorquage', 'electricite-automobile'],
    nearbyDistricts: ['Centre-ville', 'Le Logis-Neuf', 'Les Termes', 'La Gavotte', 'Saint-Antoine']
  },
  {
    slug: 'pennes-mirabeau',
    name: 'Les Pennes-Mirabeau',
    zoneSlug: 'vitrolles-marignane-martigues',
    population: '21 500 habitants',
    distance: '15 km',
    travelTime: '20 minutes',
    intro: "<strong>Les Pennes-Mirabeau (13170)</strong>, commune entre Marseille et l'aéroport de Marignane, accueille une clientèle variée incluant beaucoup de professionnels travaillant dans la zone aéroportuaire. Nos prestations <strong>flotte professionnelle et entretien programmé</strong> y sont particulièrement appréciées.",
    localContext: "La proximité de l'aéroport Marseille-Provence influence le profil automobile : nombreux taxis, VTC, livreurs aéroportuaires, et professionnels avec déplacements fréquents. Ces clients ont besoin de <strong>véhicules toujours opérationnels</strong>, ce qui justifie nos formules d'entretien préventif et nos conventions de partenariat.",
    accessInfo: "Depuis Les Pennes-Mirabeau, prenez la D113 puis l'A55 et A507 (rocade L2) avec sortie Plan-de-Cuques (20 minutes). Trajet rapide hors heures de pointe.",
    trafficNote: "L'A55 et l'A507 sont saturées le matin entre 7h30 et 9h. Privilégiez 9h30-15h ou samedi matin.",
    topServices: ['mecanique-generale', 'utilitaires', 'reprogrammation-moteur', 'depannage-remorquage'],
    nearbyDistricts: ['Centre-ville', 'La Gavotte', 'Plan-de-Campagne', 'Cadenelle', 'Bonneveine']
  },
  {
    slug: 'vitrolles',
    name: 'Vitrolles',
    zoneSlug: 'vitrolles-marignane-martigues',
    population: '34 000 habitants',
    distance: '29 km',
    travelTime: '35 minutes',
    intro: "<strong>Vitrolles (13127)</strong>, ville d'activité économique forte autour de l'étang de Berre, abrite de nombreuses entreprises industrielles et logistiques. Nos clients vitrollais sont majoritairement des <strong>professionnels en flotte</strong> et des particuliers qui apprécient nos tarifs compétitifs face aux concessionnaires aixois.",
    localContext: "L'environnement industriel de Vitrolles (zones de Couperigne, Anjoly, Estroublans) génère une demande forte pour les <strong>utilitaires, dépannage et entretien rapide</strong> des flottes professionnelles. Notre service <strong>convention pro avec facturation mensuelle</strong> est particulièrement adapté aux entreprises vitrollaises.",
    accessInfo: "Depuis Vitrolles, prenez l'A7 direction Marseille jusqu'à la rocade L2 (A507), puis sortie Plan-de-Cuques (35-40 minutes). En heures de pointe (8h-9h30 et 17h-19h), comptez 50-60 minutes.",
    trafficNote: "L'A7 est l'un des axes les plus chargés des Bouches-du-Rhône. Évitez absolument 8h-9h30 et 17h-19h. Service de récupération à domicile particulièrement apprécié sur cette zone.",
    topServices: ['utilitaires', 'mecanique-generale', 'depannage-remorquage', 'reprogrammation-moteur'],
    nearbyDistricts: ['Centre-ville', 'Le Liourat', 'Le Pontet', 'Couperigne', 'Estroublans', 'Anjoly']
  },
  {
    slug: 'marignane',
    name: 'Marignane',
    zoneSlug: 'vitrolles-marignane-martigues',
    population: '34 000 habitants',
    distance: '20 km',
    travelTime: '30 minutes',
    intro: "<strong>Marignane (13700)</strong>, ville aéroportuaire et industrielle (Airbus Helicopters), accueille une clientèle technique exigeante. Nos clients marignanais sont souvent des passionnés de mécanique et apprécient notre <strong>spécialisation reprogrammation moteur</strong> ainsi que notre approche transparente.",
    localContext: "La présence d'Airbus Helicopters et d'autres industries technologiques génère une clientèle de <strong>cadres et ingénieurs</strong> avec des exigences techniques élevées. Nos prestations <strong>reprogrammation Stage 1, décalaminage hydrogène et carrosserie premium</strong> sont fortement demandées sur ce profil.",
    accessInfo: "Depuis Marignane, prenez l'A55 direction Marseille puis A507 (rocade L2) avec sortie Plan-de-Cuques (30 minutes hors heures de pointe). Trajet bien dégagé via les autoroutes.",
    trafficNote: "L'A55 peut être saturée aux mêmes heures que l'A7 (matin et soir). Le service récupération à domicile est très apprécié des cadres marignanais.",
    topServices: ['reprogrammation-moteur', 'decalaminage-hydrogene', 'carrosserie-auto', 'mecanique-generale'],
    nearbyDistricts: ['Centre-ville', 'Notre-Dame', 'La Tapie', 'Le Jardin du Roy', 'Saint-Pierre']
  },
  {
    slug: 'cabries',
    name: 'Cabriès',
    zoneSlug: 'gardanne-aix-en-provence',
    population: '9 200 habitants',
    distance: '16 km',
    travelTime: '25 minutes',
    intro: "<strong>Cabriès (13480)</strong>, commune résidentielle entre Marseille et Aix, abrite notamment le pôle commercial Plan-de-Campagne. Nos clients cabriénois sont majoritairement des familles aisées avec des berlines et SUV nécessitant un entretien rigoureux et professionnel.",
    localContext: "Le pôle commercial Plan-de-Campagne (l'un des plus grands d'Europe) génère beaucoup de trafic et donc beaucoup d'<strong>accrochages parking et incidents carrosserie</strong>. Nos prestations <strong>débosselage, peinture localisée et pare-brise</strong> sont régulièrement demandées par notre clientèle de Cabriès.",
    accessInfo: "Depuis Cabriès, prenez l'A51 puis l'A507 (rocade L2) avec sortie Plan-de-Cuques (25 minutes). Trajet rapide via autoroute.",
    trafficNote: "Plan-de-Campagne génère du trafic le samedi entre 10h et 18h. Préférez la semaine ou le samedi matin tôt.",
    topServices: ['carrosserie-auto', 'pare-brise', 'mecanique-generale', 'reprogrammation-moteur'],
    nearbyDistricts: ['Centre-ville', 'Plan-de-Campagne', 'Les Pommiers', 'Calas']
  },
  {
    slug: 'bouc-bel-air',
    name: 'Bouc-Bel-Air',
    zoneSlug: 'gardanne-aix-en-provence',
    population: '15 000 habitants',
    distance: '17 km',
    travelTime: '25 minutes',
    intro: "<strong>Bouc-Bel-Air (13320)</strong>, commune résidentielle au sud d'Aix, est connue pour sa qualité de vie et son tissu de PME dynamique. Nos clients bouquerons nous choisissent pour notre <strong>service complet et nos délais de RDV courts</strong>, plus rapides que les concessionnaires aixois souvent saturés.",
    localContext: "Le profil automobile de Bouc-Bel-Air est marqué par les <strong>familles avec plusieurs véhicules</strong> et les professionnels libéraux. Notre service <strong>mécanique générale, distribution moteur et entretien programmé</strong> est très demandé pour la maintenance préventive.",
    accessInfo: "Depuis Bouc-Bel-Air, prenez l'A51 direction Marseille puis A507 (rocade L2) avec sortie Plan-de-Cuques (25 minutes). Itinéraire alternatif par la D6 plus pittoresque mais plus lent.",
    trafficNote: "L'A51 peut être saturée le matin entre 8h et 9h en raison des navetteurs aixois. Hors de cette plage, trajet fluide.",
    topServices: ['mecanique-generale', 'reprogrammation-moteur', 'pare-brise', 'electricite-automobile'],
    nearbyDistricts: ['Centre-ville', 'Le Pont-de-l\'Arc', 'La Salle', 'Les Cèdres']
  },
  {
    slug: 'gardanne',
    name: 'Gardanne',
    zoneSlug: 'gardanne-aix-en-provence',
    population: '21 000 habitants',
    distance: '27 km',
    travelTime: '30 minutes',
    intro: "<strong>Gardanne (13120)</strong>, ville historique du bassin minier provençal et désormais pôle technologique (École des Mines), combine clientèle ouvrière, professionnelle et académique. Notre garage est apprécié pour son <strong>rapport qualité-prix imbattable</strong> face aux concessionnaires aixois.",
    localContext: "Le tissu économique gardannais (industrie chimique, technologie, mines historiques) génère une demande variée : <strong>utilitaires pour pros, mécanique générale pour particuliers, et reprogrammation moteur</strong> pour les passionnés et étudiants ingénieurs des Mines.",
    accessInfo: "Depuis Gardanne, prenez la D6 puis l'A51 et A507 (rocade L2) avec sortie Plan-de-Cuques (30 minutes). Itinéraire bien dégagé en dehors des heures de pointe.",
    trafficNote: "Trafic intense le matin (7h30-9h) sur l'A51 en raison des navetteurs vers Marseille. Récupération à domicile largement appréciée.",
    topServices: ['mecanique-generale', 'reprogrammation-moteur', 'utilitaires', 'decalaminage-hydrogene'],
    nearbyDistricts: ['Centre-ville', 'Notre-Dame', 'Biver', 'Valabre', 'Fontvenelle']
  },
  {
    slug: 'aix-en-provence',
    name: 'Aix-en-Provence',
    zoneSlug: 'gardanne-aix-en-provence',
    population: '143 000 habitants',
    distance: '30 km',
    travelTime: '35 minutes',
    intro: "<strong>Aix-en-Provence (13100)</strong>, ville universitaire et résidentielle haut de gamme, génère une part importante de notre clientèle premium. Beaucoup de nos clients aixois nous choisissent pour <strong>éviter les tarifs concession</strong> tout en bénéficiant d'une qualité technique équivalente sur leurs véhicules haut de gamme.",
    localContext: "Le profil automobile aixois est marqué par les <strong>véhicules premium</strong> (BMW, Audi, Mercedes, Porsche, Range Rover) et une clientèle exigeante mais soucieuse du rapport qualité-prix. Nos prestations <strong>reprogrammation Stage 1, décalaminage hydrogène et carrosserie cabine</strong> sur ces véhicules représentent une part significative de notre activité aixoise.",
    accessInfo: "Depuis Aix, prenez l'A51 direction Marseille puis A507 (rocade L2) avec sortie Plan-de-Cuques (30-35 minutes hors heures de pointe). En matinée et fin de journée, comptez 45-50 minutes.",
    trafficNote: "L'axe A51-A507 est l'un des plus saturés de la région. Évitez 8h-9h30 et 17h-19h. Service de récupération à domicile très apprécié de notre clientèle aixoise pour éviter le trajet.",
    topServices: ['reprogrammation-moteur', 'decalaminage-hydrogene', 'carrosserie-auto', 'peinture-automobile'],
    nearbyDistricts: ['Cours Mirabeau', 'Mazarin', 'La Duranne', 'Pont-de-l\'Arc', 'Jas de Bouffan', 'Encagnane']
  },
  {
    slug: 'salon-de-provence',
    name: 'Salon-de-Provence',
    zoneSlug: 'salon-de-provence',
    population: '46 000 habitants',
    distance: '50 km',
    travelTime: '55 minutes',
    intro: "<strong>Salon-de-Provence (13300)</strong>, ville historique et base aérienne de la Patrouille de France, abrite une clientèle variée : militaires, agriculteurs (Crau, Camargue), commerçants. Malgré la distance, beaucoup de Salonais nous choisissent pour notre <strong>spécialisation moteur</strong> rare dans cette zone.",
    localContext: "Le contexte automobile salonais combine <strong>véhicules militaires et civils</strong>, <strong>utilitaires agricoles</strong> et <strong>flottes professionnelles</strong>. Nos prestations <strong>reprogrammation moteur, mécanique lourde sur utilitaires et carrosserie après accidents</strong> sont demandées malgré la distance avec Plan-de-Cuques.",
    accessInfo: "Depuis Salon, prenez l'A8 direction Aix puis l'A7 et A507 (rocade L2) avec sortie Plan-de-Cuques (50-60 minutes selon trafic). Service de récupération à domicile particulièrement recommandé pour cette distance.",
    trafficNote: "Distance importante : prévoyez le service de récupération si possible. Trajet plus fluide les samedis et hors vacances scolaires.",
    topServices: ['reprogrammation-moteur', 'mecanique-generale', 'utilitaires', 'carrosserie-auto'],
    nearbyDistricts: ['Centre-ville', 'La Coupole', 'Les Bressons', 'Bel Air', 'La Salle']
  },
  {
    slug: 'martigues',
    name: 'Martigues',
    zoneSlug: 'vitrolles-marignane-martigues',
    population: '49 000 habitants',
    distance: '40 km',
    travelTime: '45 minutes',
    intro: "<strong>Martigues (13500)</strong>, surnommée la \"Venise Provençale\", est une ville portuaire et industrielle (raffinage, pétrochimie). Notre clientèle martégale est majoritairement composée de professionnels du complexe pétrochimique de Berre et de particuliers attirés par notre rapport qualité-prix.",
    localContext: "La zone industrielle de Martigues-Lavéra-Berre génère une forte demande pour les <strong>utilitaires professionnels, mécanique sur flottes lourdes et services anti-pollution</strong> (FAP, EGR fortement sollicités par les conditions industrielles). Plusieurs entreprises locales ont signé des conventions partenariat avec nous.",
    accessInfo: "Depuis Martigues, prenez l'A55 direction Marseille puis A7 et A507 (rocade L2) avec sortie Plan-de-Cuques (45-55 minutes selon trafic). Récupération à domicile largement appréciée pour cette distance.",
    trafficNote: "Distance importante. L'A55 peut être chargée aux heures industrielles (6h-7h30 et 16h-17h30). Service récupération vivement recommandé.",
    topServices: ['utilitaires', 'nettoyage-fap', 'traitement-egr', 'depannage-remorquage'],
    nearbyDistricts: ['Centre historique', 'L\'Île', 'Ferrières', 'Jonquières', 'La Couronne', 'Lavéra']
  },
  {
    slug: 'saint-maximin-la-sainte-baume',
    name: 'Saint-Maximin-la-Sainte-Baume',
    zoneSlug: 'var-vaucluse-alpes-maritimes',
    population: '17 000 habitants',
    distance: '48 km',
    travelTime: '55 minutes',
    intro: "<strong>Saint-Maximin-la-Sainte-Baume (83470)</strong>, ville historique du Var entre Marseille et Toulon, accueille une population résidentielle en croissance. Nos clients saint-maximinois nous choisissent malgré la distance pour notre <strong>expertise moteur</strong> rare dans cette zone du Var.",
    localContext: "Saint-Maximin combine <strong>résidentiel pavillonnaire</strong> et <strong>activité commerciale</strong> autour de l'A8. Le profil automobile est varié : familles avec berlines, professionnels avec utilitaires, et passionnés avec véhicules sportifs. Nos services <strong>reprogrammation, décalaminage et entretien complet</strong> sont les plus demandés.",
    accessInfo: "Depuis Saint-Maximin, prenez l'A8 direction Aix puis A7 et A507 (rocade L2) avec sortie Plan-de-Cuques (55-65 minutes). Service de récupération à domicile très recommandé pour cette distance.",
    trafficNote: "Distance importante via A8. Trajet généralement fluide hors vacances scolaires et week-ends d'été.",
    topServices: ['reprogrammation-moteur', 'decalaminage-hydrogene', 'mecanique-generale', 'carrosserie-auto'],
    nearbyDistricts: ['Centre historique', 'La Pinède', 'Rougiers', 'Châteaurenard']
  },
  {
    slug: 'toulon',
    name: 'Toulon',
    zoneSlug: 'var-vaucluse-alpes-maritimes',
    population: '171 000 habitants',
    distance: '65 km',
    travelTime: '1h10',
    intro: "<strong>Toulon (83000)</strong>, préfecture du Var et grand port militaire français, génère une clientèle nombreuse mais éloignée. Nos clients toulonnais sont généralement des <strong>passionnés de mécanique</strong> ou des <strong>professionnels en flotte</strong> qui acceptent la distance pour notre expertise spécifique.",
    localContext: "Le contexte toulonnais combine <strong>militaires de la Marine, fonctionnaires et commerçants</strong>. Nous attirons principalement la clientèle pour des prestations <strong>spécialisées</strong> non disponibles localement à Toulon : reprogrammation Stage 1/2, décalaminage hydrogène certifié, et préparation véhicules de compétition.",
    accessInfo: "Depuis Toulon, prenez l'A50 direction Marseille jusqu'à la sortie La Penne-sur-Huveaune puis D4F (1h10 hors heures de pointe). Service de récupération longue distance proposé sur devis personnalisé.",
    trafficNote: "Distance significative. L'A50 est saturée le matin entre 7h-9h vers Marseille. Privilégiez le milieu de journée ou samedi. Récupération longue distance possible sur devis.",
    topServices: ['reprogrammation-moteur', 'decalaminage-hydrogene', 'voiture-rallye', 'voiture-rallye'],
    nearbyDistricts: ['Centre-ville', 'Le Mourillon', 'La Rode', 'Saint-Roch', 'La Serinette', 'Pont-du-Las']
  },
  {
    slug: 'istres',
    name: 'Istres',
    zoneSlug: 'salon-de-provence',
    population: '43 000 habitants',
    distance: '46 km',
    travelTime: '50 minutes',
    intro: "<strong>Istres (13800)</strong>, ville de l'étang de Berre avec base aérienne militaire, accueille une clientèle militaire et civile mixte. Notre garage est apprécié pour sa <strong>fiabilité et la régularité des prestations</strong>, particulièrement appréciées par notre clientèle militaire en mutation fréquente.",
    localContext: "La présence de la base aérienne 125 d'Istres-Le Tubé génère une clientèle <strong>militaire</strong> très spécifique : exigence de qualité, ponctualité, et capacité à travailler sur véhicules récents équipés ADAS. Nous proposons aussi des services adaptés aux <strong>familles civiles</strong> de la zone.",
    accessInfo: "Depuis Istres, prenez la D5 puis l'A55 et A507 (rocade L2) avec sortie Plan-de-Cuques (50-60 minutes). Service de récupération largement utilisé par notre clientèle istréenne.",
    trafficNote: "Distance significative. Trafic plus dense en début et fin de journée militaire. Service de récupération à domicile très apprécié.",
    topServices: ['mecanique-generale', 'reprogrammation-moteur', 'pare-brise', 'utilitaires'],
    nearbyDistricts: ['Centre-ville', 'Le Tubé', 'La Bayanne', 'Trigance', 'Rassuen']
  }
];
